### ISSUE TITLE
`fbrnch bugs` does not work at all

### ISSUE THREAD

**Issue by gotmax23** [juhp/hsbugzilla#18] opened 2022-11-14 00:55 UTC
``` console
$ fbrnch bugs fbrnch

= fbrnch =
fbrnch: BugzillaJSONParseError "Error in $.bugs[0]: key \"see_also\" not found"
```

I suspect this has to do with the recent RH Bugzilla update.

**Comment by juhp** [comment] 2022-11-14 04:43
Reproduced - thank you for reporting this

**Comment by juhp** [comment] 2022-11-14 06:34
Any idea what changed in RH bugzilla? I need to debug more...

I looked over the [release notes](https://bugzilla.redhat.com/page.cgi?id=release-notes.html) too.

**Comment by juhp** [comment] 2022-11-14 06:43
Actually it might be what is says: seems the `see_also` key does not appear in Bug's (by default anyway) anymore...
(Maybe I should relax the json parsing to prevent these kind of problems.)

**Comment by juhp** [comment] 2022-11-14 08:12
I opened https://bugzilla.redhat.com/show_bug.cgi?id=2142477 to confirm this change.

**Comment by juhp** [comment] 2022-11-16 04:18
It seems the Red Hat bz change is indeed intended so I will go ahead with pushing a fix and make a new release.

**Comment by juhp** [comment] 2022-11-23 04:47
Should be fixed in bugzilla-redhat-1.0.1, which I plan to push to Fedora soon.

**Closed as completed by juhp** 2022-11-23 04:47 UTC
